### ISSUE TITLE
wired image read failure

### ISSUE THREAD

**Issue by Chronostasys** [Chronostasys/Blazor.Cropper#24]
On my mac book pro, every time I tried to crop a gif file will fail on this line:    
https://github.com/Chronostasys/Blazor.Cropper/blob/5371cb211aa268c8c60782a6e921cd30bc1e05e6/Blazor.Cropper/Cropper.razor.cs#L337

Throwing following exception:  
![image](https://user-images.githubusercontent.com/49905799/127858321-9aca7c18-550c-45c7-a63d-677d90f4b313.png)
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: There is no file with ID 0. The file list may have changed.
      Error: There is no file with ID 0. The file list may have changed.
          at a (https://localhost:5001/_framework/blazor.webassembly.js:1:51328)
          at Object.readFileDataSharedMemory (https://localhost:5001/_framework/blazor.webassembly.js:1:53790)
          at Object.w [as invokeJSFromDotNet] (https://localhost:5001/_framework/blazor.webassembly.js:1:64032)
          at _mono_wasm_invoke_js_blazor (https://localhost:5001/_framework/dotnet.5.0.8.js:1:190800)
          at wasm_invoke_iiiiii (https://localhost:5001/_framework/dotnet.wasm:wasm-function[5611]:0xdda7f)
          at ves_pinvoke_method (https://localhost:5001/_framework/dotnet.wasm:wasm-function[5708]:0xdfb62)
          at interp_exec_method (https://localhost:5001/_framework/dotnet.wasm:wasm-function[2155]:0x44c08)
          at interp_runtime_invoke (https://localhost:5001/_framework/dotnet.wasm:wasm-function[7862]:0x12efff)
          at mono_jit_runtime_invoke (https://localhost:5001/_framework/dotnet.wasm:wasm-function[7347]:0x118e5f)
          at do_runtime_invoke (https://localhost:5001/_framework/dotnet.wasm:wasm-function[3304]:0x79d42)
Microsoft.JSInterop.JSException: There is no file with ID 0. The file list may have changed.
Error: There is no file with ID 0. The file list may have changed.
    at a (https://localhost:5001/_framework/blazor.webassembly.js:1:51328)
    at Object.readFileDataSharedMemory (https://localhost:5001/_framework/blazor.webassembly.js:1:53790)
    at Object.w [as invokeJSFromDotNet] (https://localhost:5001/_framework/blazor.webassembly.js:1:64032)
    at _mono_wasm_invoke_js_blazor (https://localhost:5001/_framework/dotnet.5.0.8.js:1:190800)
    at wasm_invoke_iiiiii (https://localhost:5001/_framework/dotnet.wasm:wasm-function[5611]:0xdda7f)
    at ves_pinvoke_method (https://localhost:5001/_framework/dotnet.wasm:wasm-function[5708]:0xdfb62)
    at interp_exec_method (https://localhost:5001/_framework/dotnet.wasm:wasm-function[2155]:0x44c08)
    at interp_runtime_invoke (https://localhost:5001/_framework/dotnet.wasm:wasm-function[7862]:0x12efff)
    at mono_jit_runtime_invoke (https://localhost:5001/_framework/dotnet.wasm:wasm-function[7347]:0x118e5f)
    at do_runtime_invoke (https://localhost:5001/_framework/dotnet.wasm:wasm-function[3304]:0x79d42)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[ReadRequest,Object,Object,Int32](String identifier, ReadRequest arg0, Object arg1, Object arg2, Int64 targetInstanceId)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[ReadRequest,Int32](String identifier, ReadRequest arg0)
   at Microsoft.AspNetCore.Components.Forms.SharedBrowserFileStream.CopyFileDataIntoBuffer(Int64 sourceOffset, Memory`1 destination, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Components.Forms.BrowserFileStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Blazor.Cropper.Cropper.OnParametersSetAsync() in /Users/bobxli/src/Blazor.Cropper/Blazor.Cropper/Cropper.razor.cs:line 337
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```
However, after more experiments, I found Blazor will throw the exactly same exception when I try to read the browser file directly after onchange event triggered by `InputFile` component

**Comment by Chronostasys** [comment]
turned out that the gif issue is because of dotnet5.0 rc. I update the nuget packages of the sample project and the problem gone
