### ISSUE TITLE
render-mode="Server" fails when when loading an image.

### ISSUE THREAD

**Issue by accessguru** [Chronostasys/Blazor.Cropper#33]
I created a simple razor component with your sample.  I'm using server side blazor.  The page renders, but when you click "choose file", the console reports the following error.

blazor.server.js:1 Uncaught (in promise) Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazor.Cropper.Cropper.get_WiderThanContainer()
   at Blazor.Cropper.Cropper.GetI()
   at Blazor.Cropper.Cropper.SizeChanged()
   at Blazor.Cropper.Cropper.OnSizeChangeEnd(MouseEventArgs args)
   at Blazor.Cropper.Cropper.<OnAfterRenderAsync>b__134_2(MouseEventArgs args)
   at Blazor.Cropper.Cropper.MouseUpCaller(MouseEventArgs args)
--- End of stack trace from previous location ---
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson)
    at Object.endInvokeDotNetFromJS (http://localhost/ImpactWeb/_framework/blazor.server.js:1:70618)
    at e.<anonymous> (http://localhost/ImpactWeb/_framework/blazor.server.js:10:48412)
    at http://localhost/ImpactWeb/_framework/blazor.server.js:1:26442
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (http://localhost/ImpactWeb/_framework/blazor.server.js:1:26412)
    at e.processIncomingData (http://localhost/ImpactWeb/_framework/blazor.server.js:1:24223)
    at e.connection.onreceive (http://localhost/ImpactWeb/_framework/blazor.server.js:1:17308)
    at e.<anonymous> (http://localhost/ImpactWeb/_framework/blazor.server.js:1:38200)
    at http://localhost/ImpactWeb/_framework/blazor.server.js:1:35167
    at Object.next (http://localhost/ImpactWeb/_framework/blazor.server.js:1:35272)

**Comment by Chronostasys** [comment]
Hi accessguru.  
Thanks for reporting this issue. Did you set `PureCSharpProcessing="true"`?  The cropper only works on serverside when this option was set.

**Comment by accessguru** [comment]
Yes I did set that property to true. Thanks for the quick response!  

Lawrence Mantin
(405) 887-1869

**Comment by Chronostasys** [comment]
I failed to reproduce this issue on my pc. Here's my test code https://github.com/Chronostasys/ServerSideCropperExample.  
Could you provide me a minimum project to reproduce the issue?

**Comment by accessguru** [comment]
I'll try it on Monday and let you know. Thanks again for your quick response. 

Lawrence Mantin
(405) 887-1869

**Comment by accessguru** [comment]
I appreciate you sharing this with me.  You’re code is fine, just a stupid oversight on my end.

 

Have a great week!

**Comment by Chronostasys** [comment]
Great to hear that!
