### ISSUE TITLE
MissingMethodException: Method not found: 'SixLabors.ImageSharp.Formats.IImageFormat  on Cropper.LoadImage()

### ISSUE THREAD

**Issue by brauerj-gc** [Chronostasys/Blazor.Cropper#66]
With any ABP.IO Blazor Server project using version 7.0 (dotnet and ABP) I get the following error!  I'm seem to be unable to fix it.  

Error: System.MissingMethodException: Method not found: 'SixLabors.ImageSharp.Formats.IImageFormat SixLabors.ImageSharp.Formats.ImageFormatManager.FindFormatByFileExtension(System.String)'.
   at Blazor.Cropper.Cropper.LoadImage(String ext, IBrowserFile resizedImageFile)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Blazor.Cropper.Cropper.LoadImage(String ext, IBrowserFile resizedImageFile)
   at Blazor.Cropper.Cropper.OnParametersSetAsync() in C:\Users\brauerj\source\repos\MyReport7\dependencies\Blazor.Cropper\Blazor.Cropper\Cropper.razor.cs:line 376
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

Any suggestions?

**Comment by brauerj-gc** [comment]
Now in the most basic version of a 7.0 template (calling a razor libary) I'm getting "Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: Could not find 'setVersion' ('setVersion' was undefined).
Error: Could not find 'setVersion' ('setVersion' was undefined)."

Here is a repository showing both issues:  https://github.com/brauerj-gc/CropperError-ABP7-and-dotnet7 
(browse to /cropper after loading either Blazor app)

**Comment by brauerj-gc** [comment]
It looks like the ServerSideCropperExample doesn't work either after switching to net7.0  https://github.com/Chronostasys/ServerSideCropperExample/

**Comment by saascentral** [comment]
I'm running into the same issue even though I'm not using ABP.IO. Was working a couple days ago and it started throwing after the setting the image OnInputFileChange

:Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Method not found: SixLabors.ImageSharp.Image SixLabors.ImageSharp.Image.Load(byte[],SixLabors.ImageSharp.Formats.IImageFormat&)
System.MissingMethodException: Method not found: SixLabors.ImageSharp.Image SixLabors.ImageSharp.Image.Load(byte[],SixLabors.ImageSharp.Formats.IImageFormat&)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<LoadImage>d__176](<LoadImage>d__176& )
   at Blazor.Cropper.Cropper.LoadImage(String ext, IBrowserFile resizedImageFile)
   at Blazor.Cropper.Cropper.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )

**Comment by saascentral** [comment]
Not sure if it's related to @brauerj-gc 's issue but I found out the cause of my issue with the Method Not Found error. I had another package that updated SixLabors.ImageSharp to 3.0 which caused Cropper to break. Downgrading SixLabors.ImageSharp to 2.1.3 seems to resolved my issue.

**Comment by GMatrixGames** [comment]
This workaround (what little it did) seems to completely not work as of .net 8. Using Client/Server/Shared model, and no matter the version of SixLabors.ImageSharp, even though it is loaded as a wasm module, it still fails with Method not found
![image](https://github.com/Chronostasys/Blazor.Cropper/assets/25112532/b65ea1d8-9408-4f9e-9c7b-96591050e768)
![image](https://github.com/Chronostasys/Blazor.Cropper/assets/25112532/9842eada-3ca3-423b-9d88-d41441a717a6)

**Comment by webbrain-one** [comment]
Hi, thanks for reporting this! I’ve opened [#77](https://github.com/Chronostasys/Blazor.Cropper/pull/77) to fix the `MissingMethodException` caused by the outdated ImageSharp API call in `Cropper.LoadImage()`. It updates the code to use the current API so image loading should work again on Blazor Server. Please give the PR build a try and let me know if it resolves the issue.
